
[general]
	#Number of uses before mob catcher breaks, damaged every time a mob is released, -1 disables durability, numbers above will set stack size to 1
	#Range: > -1
	net_durability = -1
	#Living Entity Blacklist
	#Entities that will not be captured, you can also use tag
	"Entity Blacklist" = ["corpse:corpse", "minecraft:wither", "minecraft:ender_dragon"]

